const InterestsList = [
  "Community & Environment",
  "Pets & Animals",
  "Support",
  "Career & Business",
  "Fashion & Beauty",
  "Tech",
  "Health & Wellbeing",
  "New Age & Spirituality",
  "Singles",
  "Arts & Culture",
  "Book Clubs",
  "Movements & Politics",
  "Fitness",
  "Games",
  "Outdoors & Adventure",
  "Socializing",
  "Music",
  "Education & Learning",
  "Hobbies & Crafts",
  "Sports & Recreation",
  "Parents & Family",
  "Food & Drink",
  "Religion & Beliefs",
  "LGBT",
  "Sci-Fi & Fantasy",
  "Language & Ethnic Identity",
  "Writing",
  "Photography",
  "Dancing",
  "Movies & Film",
  "Cars & Motorcycles",
];

export { InterestsList };
